// flow-typed signature: 98cd441387f8a4cc44d716323e04454f
// flow-typed version: <<STUB>>/json-api_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-api' {
  declare type JsonApiResourceId<Type: string> = {
    id: string,
    type: Type
  };

  declare type JsonApiResource<Type, Attributes = Object> = {
    ...JsonApiResourceId<Type>,
    attributes?: Attributes,
    relationships?: Object,
    links?: Object,
    meta?: Object
  };

  declare type JsonApiDocument<PrimaryResourceTypes> = {
    data: PrimaryResourceTypes | Array<PrimaryResourceTypes> | null,
  };
}
