// flow-typed signature: 07b633789771a4d85bf92979d67d48d6
// flow-typed version: <<STUB>>/redux-json-api_v^2.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-json-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-json-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-json-api/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-json-api/lib/jsonapi' {
  declare module.exports: any;
}

declare module 'redux-json-api/lib/state-mutation' {
  declare module.exports: any;
}

declare module 'redux-json-api/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-json-api/test/jsonapi' {
  declare module.exports: any;
}

declare module 'redux-json-api/test/link-payload' {
  declare module.exports: any;
}

declare module 'redux-json-api/test/payloads/failingReverseRelationshipUpdate' {
  declare module.exports: any;
}

declare module 'redux-json-api/test/state-mutation' {
  declare module.exports: any;
}

declare module 'redux-json-api/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-json-api/lib/constants.js' {
  declare module.exports: $Exports<'redux-json-api/lib/constants'>;
}
declare module 'redux-json-api/lib/jsonapi.js' {
  declare module.exports: $Exports<'redux-json-api/lib/jsonapi'>;
}
declare module 'redux-json-api/lib/state-mutation.js' {
  declare module.exports: $Exports<'redux-json-api/lib/state-mutation'>;
}
declare module 'redux-json-api/lib/utils.js' {
  declare module.exports: $Exports<'redux-json-api/lib/utils'>;
}
declare module 'redux-json-api/test/jsonapi.js' {
  declare module.exports: $Exports<'redux-json-api/test/jsonapi'>;
}
declare module 'redux-json-api/test/link-payload.js' {
  declare module.exports: $Exports<'redux-json-api/test/link-payload'>;
}
declare module 'redux-json-api/test/payloads/failingReverseRelationshipUpdate.js' {
  declare module.exports: $Exports<'redux-json-api/test/payloads/failingReverseRelationshipUpdate'>;
}
declare module 'redux-json-api/test/state-mutation.js' {
  declare module.exports: $Exports<'redux-json-api/test/state-mutation'>;
}
declare module 'redux-json-api/test/utils.js' {
  declare module.exports: $Exports<'redux-json-api/test/utils'>;
}
